recipe: default.v1
language: de
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: openai_direct
  flow_retrieval:
    embeddings:
      model_group: openai_embeddings
  user_input:
    max_characters: 420

policies:
- name: FlowPolicy
assistant_id: 20250319-144006-sour-pulsar
